# Algoritmos de otimização - transporte de produtos

O exercício consiste em MAXIMIZAR o lucro de uma empresa de transportes



*   Cada caminhão possui apenas 3m3 de espaço em seu baú
*   Cada produto possui um nome, um voluma (em m3) e um preço
*   É preciso maximizar o lucro em relação ao volume e o transporte não pode ocorrer com mais de 3m3 de itens
*   É preciso implementar a fitness_funcion que retorna o custo de uma solução
*   Você possui apenas um produto de cada para transportar no caminhão





**Lista de produtos, volume, preço**


'Refrigerador A', 0.751, 999.90

'Refrigerador B', 0.635, 849.00

'Refrigerador C', 0.870, 1199.89

'Celular', 0.0000899, 2911.12

'TV 55', 0.400, 4346.99

'TV 50', 0.290, 3999.90

'TV 42', 0.200, 2999.00

'Ventilador', 0.496, 199.90

'Microondas A', 0.0424, 308.66

'Microondas B', 0.0544, 429.90

'Microondas C', 0.0319, 299.29

'Notebook A', 0.00350, 2499.90

'Notebook B', 0.498, 1999.90

'Notebook C', 0.527, 3999.00

In [1]:
!pip install mlrose

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
from prettytable import PrettyTable
import six
import sys
sys.modules['sklearn.externals.six'] = six
import mlrose

## Representação do problema

In [3]:
# definição da lista de procuros, volume e preço:

produtos = [('Refrigerador A', 0.751, 999.90),
            ('Refrigerador B', 0.635, 849.00),
            ('Refrigerador C', 0.870, 1199.89),
            ('Celular', 0.0000899, 2911.12),
            ('TV 55', 0.400, 4346.99),
            ('TV 50', 0.290, 3999.90),
            ('TV 42', 0.200, 2999.00),
            ('Ventilador', 0.496, 199.90),
            ('Microondas A', 0.0424, 308.66),
            ('Microondas B', 0.0544, 429.90),
            ('Microondas C', 0.0319, 299.29),
            ('Notebook A', 0.00350, 2499.90),
            ('Notebook B', 0.498, 1999.90),
            ('Notebook C', 0.527, 3999.00)]

# espação no caminhão:        
espaco_disponivel = 3

In [4]:
print(produtos[0]) #primeiro produto da lista
print(produtos[0][0]) #nome do primeiro produto da lista
print(produtos[0][1]) #vaolume do primeiro produto da lista
print(produtos[0][2]) #preço do primeiro produto da lista

('Refrigerador A', 0.751, 999.9)
Refrigerador A
0.751
999.9


A representação da solução pode ser feita por "zeros" e "uns" indicando se um produto deve ou não ser incluído no caminhão

In [5]:
def imprimir_solucao(solucao):
  tabela = PrettyTable(['Produto', 'Volume', 'Preço'])
  volume_total = 0
  preco_total = 0
  for i in range(len(solucao)):
    if solucao[i] == 1:
      volume_total += produtos[i][1]
      preco_total += produtos[i][2]
      tabela.add_row([produtos[i][0], produtos[i][1], produtos[i][2]])
  print(tabela)
  print(f'Volume ocupado: {volume_total}')
  print(f'Valor total: {preco_total}')

In [6]:
imprimir_solucao([1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1])
#imprimir_solucao([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

+----------------+----------+---------+
|    Produto     |  Volume  |  Preço  |
+----------------+----------+---------+
| Refrigerador A |  0.751   |  999.9  |
| Refrigerador B |  0.635   |  849.0  |
| Refrigerador C |   0.87   | 1199.89 |
|    Celular     | 8.99e-05 | 2911.12 |
|     TV 50      |   0.29   |  3999.9 |
|     TV 42      |   0.2    |  2999.0 |
|  Microondas A  |  0.0424  |  308.66 |
|  Microondas B  |  0.0544  |  429.9  |
|  Microondas C  |  0.0319  |  299.29 |
|   Notebook C   |  0.527   |  3999.0 |
+----------------+----------+---------+
Volume ocupado: 3.4017899000000003
Valor total: 17995.66


In [7]:
def fitness_function(solucao):
  preco_total = 0
  volume_total = 0
  for i in range(len(solucao)):
    if solucao[i] == 1:
      preco_total += produtos[i][2]
      volume_total += produtos[i][1]
  if volume_total > espaco_disponivel:
    preco_total = 1 # é um controle, pois o custo 1 é ruim para o algoritmo
  return preco_total

In [8]:
fitness_function([0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1])
fitness_function([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

1

In [9]:
fitness = mlrose.CustomFitness(fitness_function)

In [10]:
problema = mlrose.DiscreteOpt(length = 14, fitness_fn = fitness, 
                             maximize = True, max_val = 2)

## Hill climb

In [11]:
melhor_solucao, melhor_custo = mlrose.hill_climb(problema)
melhor_solucao, melhor_custo

(array([1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1]), 20994.55)

In [12]:
imprimir_solucao(melhor_solucao)

+----------------+----------+---------+
|    Produto     |  Volume  |  Preço  |
+----------------+----------+---------+
| Refrigerador A |  0.751   |  999.9  |
| Refrigerador C |   0.87   | 1199.89 |
|    Celular     | 8.99e-05 | 2911.12 |
|     TV 55      |   0.4    | 4346.99 |
|     TV 50      |   0.29   |  3999.9 |
|  Microondas A  |  0.0424  |  308.66 |
|  Microondas B  |  0.0544  |  429.9  |
|  Microondas C  |  0.0319  |  299.29 |
|   Notebook A   |  0.0035  |  2499.9 |
|   Notebook C   |  0.527   |  3999.0 |
+----------------+----------+---------+
Volume ocupado: 2.9702899
Valor total: 20994.55


## Simulated annealing

In [13]:
melhor_solucao, melhor_custo = mlrose.simulated_annealing(problema)
melhor_solucao, melhor_custo

/usr/local/lib/python3.7/dist-packages/mlrose/algorithms.py:311: RuntimeWarning: overflow encountered in exp
  prob = np.exp(delta_e/temp)


(array([0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0]), 14388.8)

In [14]:
imprimir_solucao(melhor_solucao)

+----------------+----------+---------+
|    Produto     |  Volume  |  Preço  |
+----------------+----------+---------+
| Refrigerador B |  0.635   |  849.0  |
| Refrigerador C |   0.87   | 1199.89 |
|    Celular     | 8.99e-05 | 2911.12 |
|     TV 50      |   0.29   |  3999.9 |
|   Ventilador   |  0.496   |  199.9  |
|  Microondas B  |  0.0544  |  429.9  |
|  Microondas C  |  0.0319  |  299.29 |
|   Notebook A   |  0.0035  |  2499.9 |
|   Notebook B   |  0.498   |  1999.9 |
+----------------+----------+---------+
Volume ocupado: 2.8788899
Valor total: 14388.8


## Algoritmo genético

In [15]:
melhor_solucao, melhor_custo = mlrose.genetic_alg(problema, pop_size=1000, mutation_prob=0.2)
melhor_solucao, melhor_custo

(array([0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1]), 24993.550000000003)

In [16]:
imprimir_solucao(melhor_solucao)

+----------------+----------+---------+
|    Produto     |  Volume  |  Preço  |
+----------------+----------+---------+
| Refrigerador C |   0.87   | 1199.89 |
|    Celular     | 8.99e-05 | 2911.12 |
|     TV 55      |   0.4    | 4346.99 |
|     TV 50      |   0.29   |  3999.9 |
|     TV 42      |   0.2    |  2999.0 |
|  Microondas A  |  0.0424  |  308.66 |
|  Microondas B  |  0.0544  |  429.9  |
|  Microondas C  |  0.0319  |  299.29 |
|   Notebook A   |  0.0035  |  2499.9 |
|   Notebook B   |  0.498   |  1999.9 |
|   Notebook C   |  0.527   |  3999.0 |
+----------------+----------+---------+
Volume ocupado: 2.9172899
Valor total: 24993.550000000003
