# Matrizes

In [3]:
import numpy as np #numpy é muito utilizada para processamento cintífico (MUITO usada em IA)

In [4]:
matriz = np.array([[2, 3, 1],
                   [4, 5, 7]]) #matriz 2x3

In [5]:
print(matriz)

[[2 3 1]
 [4 5 7]]


In [6]:
matriz.shape #mostra o formato da estrutura

(2, 3)

In [7]:
matriz[0] #primeira linha


array([2, 3, 1])

In [8]:
matriz[1]

array([4, 5, 7])

In [9]:
matriz[0][2]

1

In [10]:
matriz[1][0]

4

In [11]:
matriz.shape

(2, 3)

In [12]:
for i in range(matriz.shape[0]):
  print(matriz[i])
  for j in range(matriz.shape[1]):
    print(matriz[i][j])

[2 3 1]
2
3
1
[4 5 7]
4
5
7


# Exercícios de fixação


1. Lista: Crie uma estrutura de repetição para fazer a leitura de 5 números inteiros e os armazene dentro de uma lista. Após a leitura, crie outra estrutura de repetição para somar todos os valores digitados

2. Dicionário: Crie um dicionário para armazenar o nome e a nota de 3 alunos, fazendo a leitura dos valores por meio de uma estrutura de repetição. Depois, crie uma nova estrutura de repetição para somar todas as notas e retornar a média

3. Matriz: Dada a matriz abaixo, construa uma estrutura de repetição para percorrer e somar todos os elementos da matriz

matriz = np.array([[3, 4, 1],
                   [3, 1, 5]])

# Resolução dos exercícios

## Execício 1

In [13]:
lista = []
for _ in range(1, 6):
  valor = int(input('Informe o valor: '))
  lista.append(valor)

Informe o valor: 1
Informe o valor: 2
Informe o valor: 5
Informe o valor: 6
Informe o valor: 7


In [14]:
lista

[1, 2, 5, 6, 7]

In [15]:
len(lista)

5

In [16]:
soma = 0
for i in range(len(lista)):
  #print(soma)
  soma += lista[i]
print('Soma:', soma)

Soma: 21


In [17]:
import numpy as np

In [18]:
np.array(lista).sum() #alternativa usando o numpy

21

## Exercício 2

In [19]:
alunos = {}
for _ in range(1, 4):
  nome = input('Infome o nome do aluno: ')
  nota = float(input(f'Infome a nota do aluno {nome}: '))
  alunos[nome] = nota

Infome o nome do aluno: Thiago
Infome a nota do aluno Thiago: 9
Infome o nome do aluno: Diego
Infome a nota do aluno Diego: 6.5
Infome o nome do aluno: Leonardo
Infome a nota do aluno Leonardo: 10


In [21]:
alunos

{'Diego': 6.5, 'Leonardo': 10.0, 'Thiago': 9.0}

In [22]:
soma = 0
for nota in alunos.values():
  soma += nota
print('A soma de notas é: ', soma)
print('A média das notas é', soma / 3)

A soma de notas é:  25.5
A média das notas é 8.5


## Exercício 3

In [23]:
matriz = np.array([[3, 4, 1],
                   [3, 1, 5]])

In [24]:
matriz

array([[3, 4, 1],
       [3, 1, 5]])

In [26]:
matriz.shape

(2, 3)

In [28]:
soma = 0
for i in range(matriz.shape[0]):
  for j in range(matriz.shape[1]):
    soma += matriz[i][j]

print('Soma: ', soma)

Soma:  17
